<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .task-id{width:2%} .task-name{width:30%}

</style>

<table>
    <tr>
        <th class="task-id">Id</th>
        <th class="task-name">Name</th>
    </tr>
    <?php
    foreach ($block->getTaskCollection() as $key=>$task){
        echo '<tr>
                    <td>'.$task->getId().'</td>
                    <td>'.$task->getName().'</td>
                  </tr>';
    }
    ?>
</table>
